import { Language, Plan } from './types';

export const PLANS: Plan[] = [
  { id: 'trial', durationMonths: 0.25, priceStars: 0, isTrial: true, name: '7 Days Trial' },
  { id: '1m', durationMonths: 1, priceStars: 200, isTrial: false, name: '1 Month' },
  { id: '3m', durationMonths: 3, priceStars: 400, isTrial: false, name: '3 Months' },
  { id: '6m', durationMonths: 6, priceStars: 600, isTrial: false, name: '6 Months' },
  { id: '12m', durationMonths: 12, priceStars: 1000, isTrial: false, name: '12 Months' },
  { id: '24m', durationMonths: 24, priceStars: 1500, isTrial: false, name: '24 Months' },
];

export const TRANSLATIONS = {
  [Language.EN]: {
    home: 'Home',
    profile: 'Profile',
    totalUsers: 'Total Users Protected',
    buy: 'Buy',
    free: 'Free',
    stars: 'Stars',
    activeUntil: 'Active until',
    expired: 'Expired',
    renew: 'Renew Subscription',
    yourId: 'Your ID',
    referralLink: 'Referral Link',
    inviteText: 'Invite a friend and get 1 month free when they buy a subscription!',
    language: 'Language',
    getVpn: 'Get Access',
    setupInstructions: 'Setup Instructions',
    copy: 'Copy',
    copied: 'Copied!',
    trialUsed: 'Trial Used',
    extend: 'Extend',
    warning: 'Expires soon!',
    refCount: 'Friends Invited',
  },
  [Language.RU]: {
    home: 'Главная',
    profile: 'Профиль',
    totalUsers: 'Всего пользователей',
    buy: 'Купить',
    free: 'Бесплатно',
    stars: 'Звёзд',
    activeUntil: 'Активна до',
    expired: 'Истекла',
    renew: 'Продлить подписку',
    yourId: 'Ваш ID',
    referralLink: 'Реферальная ссылка',
    inviteText: 'Пригласи друга и получи 1 месяц бесплатно, когда он купит подписку!',
    language: 'Язык',
    getVpn: 'Получить доступ',
    setupInstructions: 'Инструкция по настройке',
    copy: 'Коп.',
    copied: 'Скопировано!',
    trialUsed: 'Использован',
    extend: 'Продлить',
    warning: 'Скоро истекает!',
    refCount: 'Приглашено друзей',
  },
  [Language.ZH]: {
    home: '首页',
    profile: '个人资料',
    totalUsers: '总用户数',
    buy: '购买',
    free: '免费',
    stars: 'Stars',
    activeUntil: '有效期至',
    expired: '已过期',
    renew: '续订',
    yourId: '您的 ID',
    referralLink: '推荐链接',
    inviteText: '邀请朋友，当他们购买订阅时，您将获得1个月的免费VPN！',
    language: '语言',
    getVpn: '获取访问权限',
    setupInstructions: '设置说明',
    copy: '复制',
    copied: '已复制!',
    trialUsed: '已试用',
    extend: '延长',
    warning: '即将到期!',
    refCount: '邀请好友',
  },
};
